DROP TABLE IF EXISTS actions CASCADE;

CREATE TABLE IF NOT EXISTS apps (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(30) NOT NULL,

  CONSTRAINT pk_apps PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS actions (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  app_id bigint NOT NULL REFERENCES apps(id),
  uri varchar(100) NOT NULL,
  ip varchar(15) NOT NULL,
  timestamp timestamp NOT NULL,

  CONSTRAINT pk_actions PRIMARY KEY (id)
);